- id: ktlint
  name: 'ktlint'
  entry: run-ktlint.sh
  language: 'script'
  files: '\.kt[s]?$'
  description: "Runs `ktlint`, need install ktlint first"
- id: swiftlint
  name: SwiftLint
  description: "Check Swift files for issues with SwiftLint"
  entry: run-swiftlint.sh
  language: script
  types: [swift]
